version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://localhost:3005
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev:client

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev:server

networks:
  default:
    driver: bridge