name: Trigger Netlify Deploy

on:
  push:
    branches: [ main ]

jobs:
  trigger-netlify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build via build hook
        run: |
          if [ -z "${{ secrets.NETLIFY_BUILD_HOOK }}" ]; then
            echo "NETLIFY_BUILD_HOOK secret is not set. Skipping Netlify trigger.";
            exit 0;
          fi
          curl -X POST "${{ secrets.NETLIFY_BUILD_HOOK }}"
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
